version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - springboot-network
    volumes:
      - redis-data:/data

networks:
  springboot-network:
    driver: bridge

volumes:
  redis-data:
